<a href="https://colab.research.google.com/github/michellaanjani/LAB/blob/main/2702238470_MICHELLA_LAB01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world


//hello world

In [ ]:
import time
time.ctime()

'Tue Feb  6 07:01:07 2024'

In [ ]:
x = 1
y = 2 + x
x = 2
y

3

In [ ]:
x

2

In [ ]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
y = np.array([[1,4,3],[3,2,7]])
y

array([[1, 4, 3],
       [3, 2, 7]])

In [ ]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
p = np.array([[[1,2,3],[4,5,6],[5,6,7]]])
p

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]]])

In [ ]:
t = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
t

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
def myFunction (a,b,c):
  """
  function to sum the 3 numbers
  input: 3 numbers a,b,c
  output: the sum of a, b, and c
  """
  #koko
  out = a + b+ c
  return out

In [ ]:
help(myFunction)

Help on function myFunction in module __main__:

myFunction(a, b, c)
    function to sum the 3 numbers
    input: 3 numbers a,b,c
    output: the sum of a, b, and c



In [ ]:
o = myFunction(2,3,4)

9

In [ ]:
def thermo(temp,desired_temp):
  if temp < desired_temp - 5:
    status = 'Heat'
  elif temp > desired_temp + 5:
    status = 'AC'
  else:
    status = 'Off'
  return status




In [ ]:
status = thermo(7,2)
print(status)

Off


In [ ]:
x = 3
if x > 1 and x < 2:
  y = 2
elif x > 2 and x < 4:
  y = 4
else:
  y = 0
y



4

In [ ]:
x = 3
if 1 < x < 2:
  y = 2
elif 2 < x < 4:
  y = 4
else:
  y = 0
y

4